# Generated by Django 5.2.13 on 2026-04-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Tashkilot nomi')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Qisqa nomi')),
                ('org_type', models.CharField(choices=[('ministry', 'Vazirlik'), ('committee', "Qo'mita"), ('agency', 'Agentlik'), ('company', 'Korxona'), ('bank', 'Bank'), ('hokimlik', 'Hokimlik'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Turi')),
                ('openness_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ochiqlik balli')),
                ('category', models.CharField(choices=[('green', '🟢 Yashil (71-100)'), ('yellow', '🟡 Sariq (55-71)'), ('red', '🔴 Qizil (0-55)')], default='yellow', max_length=10, verbose_name='Kategoriya')),
                ('rank', models.IntegerField(default=0, verbose_name="Reyting o'rni")),
                ('score_2024', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='2024-yil ball')),
                ('score_2023', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='2023-yil ball')),
                ('trend', models.CharField(choices=[('up', "📈 O'sish"), ('down', '📉 Pasayish'), ('stable', '➡️ Stabil')], default='stable', max_length=10, verbose_name='Trend')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Risk balli (AI)')),
                ('employees_count', models.IntegerField(default=0, verbose_name='Xodimlar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlar',
                'ordering': ['rank', '-openness_score'],
            },
        ),
    ]
