# Generated by Django 5.2.13 on 2026-04-24 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ismi")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='officials/', verbose_name='Rasm')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('position', models.CharField(max_length=200, verbose_name='Lavozim')),
                ('position_level', models.CharField(choices=[('top', 'Yuqori lavozim (vazir, gubernator)'), ('senior', "Yuqori amaldor (o'rinbosar, bosh)"), ('middle', "O'rta lavozim (bo'lim boshlig'i)"), ('regular', 'Oddiy xodim')], default='middle', max_length=20, verbose_name='Daraja')),
                ('appointed_date', models.DateField(blank=True, null=True, verbose_name='Tayinlangan sana')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Oylik maosh (so'm)")),
                ('declared_income', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Deklaratsiya daromadi (yillik)')),
                ('declared_assets', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Deklaratsiya aktivlari')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Risk balli (0-100)')),
                ('risk_level', models.CharField(choices=[('low', '🟢 Past risk'), ('medium', "🟡 O'rta risk"), ('high', '🟠 Yuqori risk'), ('critical', '🔴 Kritik risk')], default='low', max_length=20, verbose_name='Risk darajasi')),
                ('income_mismatch_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Daromad nomuvofiqligi')),
                ('lifestyle_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Hayot tarzi riski')),
                ('network_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tarmoq riski')),
                ('wealth_growth_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Boylik o'sishi riski")),
                ('risk_explanation', models.TextField(blank=True, verbose_name='AI tushuntirish')),
                ('red_flags', models.JSONField(blank=True, default=list, verbose_name='Red flags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Amaldor',
                'verbose_name_plural': 'Amaldorlar',
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('real_estate', "🏠 Ko'chmas mulk"), ('vehicle', '🚗 Transport vositasi'), ('luxury', '💎 Hashamatli buyum'), ('business', '🏢 Biznes'), ('foreign', '🌍 Xorijiy aktiv'), ('other', '📦 Boshqa')], max_length=20, verbose_name='Turi')),
                ('name', models.CharField(max_length=300, verbose_name='Nomi')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Qiymati (so'm)")),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Joylashuvi')),
                ('is_declared', models.BooleanField(default=False, verbose_name='Deklaratsiyada')),
                ('is_luxury', models.BooleanField(default=False, verbose_name='Hashamatli')),
                ('owner_name', models.CharField(blank=True, help_text="Agar qarindoshi nomida bo'lsa", max_length=200, verbose_name='Rasmiy egasi')),
                ('discovered_date', models.DateField(auto_now_add=True, verbose_name='Aniqlangan sana')),
                ('source', models.CharField(blank=True, help_text='Kadastr, OSINT, soc. tarmoq va h.k.', max_length=200, verbose_name='Manba')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='officials.official')),
            ],
            options={
                'verbose_name': 'Aktiv',
                'verbose_name_plural': 'Aktivlar',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ismi')),
                ('relation_type', models.CharField(choices=[('spouse', "Turmush o'rtoq"), ('child', 'Farzand'), ('parent', 'Ota-ona'), ('sibling', 'Aka-uka/opa-singil'), ('in_law', 'Qayin qarindosh'), ('other', 'Boshqa')], max_length=20, verbose_name='Qarindoshlik')),
                ('has_business', models.BooleanField(default=False, verbose_name='Biznesi bor')),
                ('business_name', models.CharField(blank=True, max_length=300, verbose_name='Biznes nomi')),
                ('business_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Biznes qiymati')),
                ('has_government_tenders', models.BooleanField(default=False, verbose_name='Davlat tenderlari')),
                ('total_tenders_won', models.IntegerField(default=0, verbose_name='Yutgan tenderlar soni')),
                ('total_tender_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Umumiy tender qiymati')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='officials.official')),
            ],
            options={
                'verbose_name': 'Qarindosh',
                'verbose_name_plural': 'Qarindoshlar',
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tender nomi')),
                ('company_name', models.CharField(max_length=300, verbose_name='Yutgan kompaniya')),
                ('company_owner', models.CharField(blank=True, max_length=200, verbose_name='Kompaniya egasi')),
                ('value', models.DecimalField(decimal_places=2, max_digits=18, verbose_name="Qiymati (so'm)")),
                ('announced_date', models.DateField(verbose_name="E'lon qilingan sana")),
                ('awarded_date', models.DateField(verbose_name="G'olib bo'lgan sana")),
                ('is_suspicious', models.BooleanField(default=False, verbose_name='Shubhali')),
                ('price_vs_market', models.DecimalField(decimal_places=2, default=0, help_text="Masalan 35% yuqori bo'lsa shubhali", max_digits=6, verbose_name='Bozor narxidan %')),
                ('linked_relative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='officials.relative')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Tender',
                'verbose_name_plural': 'Tenderlar',
                'ordering': ['-awarded_date'],
            },
        ),
    ]
